# =============================================================================
# Site settings
# =============================================================================
title: Siyuan’s Journal
subtitle: >-
  “The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.”
——Albert Einstein
email: sikyuan@outlook.com
description: >-
  一名来自中国的高中生，热爱探索科技与人文的交汇点。正在努力学习数理与编程，希望未来能在人工智能或工程技术领域做出自己的贡献。
url: "https://synr1xhone.github.io" # 你的博客网址
baseurl: "" # 保持为空
repository: "synr1xhone/synr1xhone.github.io" # 你的仓库地址
teaser: "/assets/images/siyuan-avatar.jpg" # 首页摘要图，使用你的头像
logo: "/assets/icons/favicon.ico" # 网站小图标
github_username: synr1xhone
minimal_mistakes_skin: dark # 深色主题皮肤
search: true
breadcrumbs: true
words_per_minute: 183

# =============================================================================
# Build settings
# =============================================================================
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /blog/page:num
timezone: Asia/Shanghai # 你的时区

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# =============================================================================
# Author Defaults
# =============================================================================
author:
  name    : "siyuan"
  avatar  : "/assets/images/siyuan-avatar.jpg" # 你的头像路径
  bio     : "A high school student from Zhuhai, China, learning math and programming with curiosity and determination."
  location: "珠海, 中国"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/synr1xhone"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sikyuan@outlook.com"

# =============================================================================
# Footer Links
# =============================================================================
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/synr1xhone"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sikyuan@outlook.com"

# =============================================================================
# Defaults
# =============================================================================
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      date_format: "%Y-%m-%d"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
