# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: George's Blog
subtitle: >-
  Undergraduate Student @ Univ. of Mass. Amherst, CICS.
email: georgezuo888@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Zhiyang (George) Zuo's Personal Website, Portfolio, and Blog
url: "https://zzuo123.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
repository: "zzuo123/zzuo123.github.io" # the GitHub repository hosting your site
teaser: "/assets/images/bio-photo.jpg" # Used to generate absolute URL to image on homepage.
logo: "/assets/icons/favicon.ico"
# twitter_username: username
github_username: zzuo123
minimal_mistakes_skin: dark
search: true
breadcrumbs: true
words_per_minute: 183 # average readers can read 183 words per minute

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name    : "Zhiyang Zuo"
  avatar  : "/assets/images/bio-photo.jpg"
  bio     : "Undergraduate Student @ Univ. of Mass. Amherst, CICS."
  location: "Amherst, MA"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zzuo123"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zhiyangzuo/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/@georgezuo4620"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/george.zuo01"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:georgezuo888@gmail.com"
    - label: "Resume"
      icon: "fas fa-fw fa-file"
      url: "/assets/files/resume.pdf"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zzuo123"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zhiyangzuo/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:georgezuo888@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      date_format: "%Y-%m-%d"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
